import { jsPDF } from 'jspdf';

interface StyleGuideData {
  logoUrl: string | null;
  colors: {
    primary: string;
    secondary: string;
  };
  contrastRatio: {
    ratio: number;
    rating: string;
  };
  assets: Record<string, string>;
}

export const generateStyleGuide = async (data: StyleGuideData) => {
  const { logoUrl, colors, contrastRatio, assets } = data;
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // Helper to convert hex to rgb
  const hexToRgb = (hex: string) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return { r, g, b };
  };

  const primaryRgb = hexToRgb(colors.primary);
  const secondaryRgb = hexToRgb(colors.secondary);

  // Header
  doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Brand Style Guide', margin, 25);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Entra ID Branding Generator', margin, 32);

  let currentY = 60;

  // 1. Logo Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Organization Logo', margin, currentY);
  currentY += 10;

  if (logoUrl) {
    try {
      // Assuming logoUrl is a data URL or accessible URL
      doc.addImage(logoUrl, 'PNG', margin, currentY, 40, 40, undefined, 'FAST');
    } catch {
      doc.setFontSize(10);
      doc.text('[Logo Image]', margin, currentY + 10);
    }
  } else {
    doc.setFontSize(10);
    doc.text('No logo provided', margin, currentY);
  }
  currentY += 50;

  // 2. Color Palette
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Color Palette', margin, currentY);
  currentY += 10;

  // Primary Color Box
  doc.setFillColor(primaryRgb.r, primaryRgb.g, primaryRgb.b);
  doc.rect(margin, currentY, 30, 30, 'F');
  doc.setDrawColor(200, 200, 200);
  doc.rect(margin, currentY, 30, 30, 'S');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Primary Color', margin + 35, currentY + 5);
  doc.setFont('helvetica', 'normal');
  doc.text(`HEX: ${colors.primary.toUpperCase()}`, margin + 35, currentY + 12);
  doc.text(`RGB: ${primaryRgb.r}, ${primaryRgb.g}, ${primaryRgb.b}`, margin + 35, currentY + 19);

  // Secondary Color Box
  const secondColX = margin + 100;
  doc.setFillColor(secondaryRgb.r, secondaryRgb.g, secondaryRgb.b);
  doc.rect(secondColX, currentY, 30, 30, 'F');
  doc.rect(secondColX, currentY, 30, 30, 'S');
  
  doc.setFont('helvetica', 'bold');
  doc.text('Secondary Color', secondColX + 35, currentY + 5);
  doc.setFont('helvetica', 'normal');
  doc.text(`HEX: ${colors.secondary.toUpperCase()}`, secondColX + 35, currentY + 12);
  doc.text(`RGB: ${secondaryRgb.r}, ${secondaryRgb.g}, ${secondaryRgb.b}`, secondColX + 35, currentY + 19);

  currentY += 45;

  // 3. Accessibility
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Accessibility & Contrast', margin, currentY);
  currentY += 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Contrast Ratio (Primary vs White): ${contrastRatio.ratio.toFixed(2)}:1`, margin, currentY);
  currentY += 7;
  
  const ratingColor = contrastRatio.rating === 'Fail' ? [200, 0, 0] : [0, 150, 0];
  doc.setTextColor(ratingColor[0], ratingColor[1], ratingColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text(`WCAG Rating: ${contrastRatio.rating}`, margin, currentY);
  doc.setTextColor(0, 0, 0);
  currentY += 15;

  // 4. Asset Previews
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Branding Assets', margin, currentY);
  currentY += 10;

  const assetKeys = ['squareLight', 'squareDark', 'banner'];
  let assetX = margin;
  assetKeys.forEach((key) => {
    if (assets[key]) {
      try {
        doc.addImage(assets[key], 'PNG', assetX, currentY, 30, 30, undefined, 'FAST');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(key, assetX, currentY + 35);
      } catch {
        // skip
      }
    }
    assetX += 45;
  });
  currentY += 50;

  // 5. Login Mockup Preview
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Login Experience Preview', margin, currentY);
  currentY += 10;

  // Mockup box
  const mockupWidth = 120;
  const mockupHeight = 60;
  const mockupX = (pageWidth - mockupWidth) / 2;
  
  // Background
  if (assets.background) {
    try {
      doc.addImage(assets.background, 'PNG', mockupX, currentY, mockupWidth, mockupHeight, undefined, 'FAST');
    } catch {
      doc.setFillColor(240, 240, 240);
      doc.rect(mockupX, currentY, mockupWidth, mockupHeight, 'F');
    }
  } else {
    doc.setFillColor(240, 240, 240);
    doc.rect(mockupX, currentY, mockupWidth, mockupHeight, 'F');
  }

  // Login form overlay
  doc.setFillColor(255, 255, 255, 0.9);
  doc.rect(mockupX + 70, currentY + 5, 40, 50, 'F');
  
  // Banner/Logo in form
  if (assets.banner) {
    try {
      doc.addImage(assets.banner, 'PNG', mockupX + 75, currentY + 10, 30, 10, undefined, 'FAST');
    } catch {}
  }

  doc.save('brand-style-guide.pdf');
};
